version: "3"
services:
  master:
    image: jenkins/jenkins:lts
    ports:
      - "50000:50000"
    networks:
      - jenkins-net
    expose: 
      - "8080"

  nginx:
    build: ./nginx
    ports:
      - "8888:8888"
      - "443:443"
    depends_on:
      - master
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge
