version: "3"
services:
  master:
    build: ./jenkins
    ports:
      - "50000:50000"
      - "8888:8080"
    networks:
      - jenkins-net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - master
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge
